{{
  config(
    materialized = "view"
  )
}}

 SELECT ORDRAW.ORDER_ID, 
 ORDRAW.CUSTOMER_ID ,
 ORDRAW.ORDER_STATUS,
 ORDRAW.ORDER_PURCHASE_TIMESTAMP,
 ORDRAW.ORDER_ESTIMATED_DELIVERY_DATE,
 --CUSTRAW.CUSTOMER_ID,
CUSTRAW.CUSTOMER_UNIQUE_ID,
CONCAT(CUSTRAW.CUSTOMER_STATE,' _ ', CUSTRAW.CUSTOMER_CITY,' _ ', CUSTRAW.CUSTOMER_ZIP_CODE_PREFIX) AS CUSTOMER_ADDRESS
 FROM {{ref('orders_raw_v')}}  ORDRAW
INNER JOIN {{ref('customer_raw_v')}} CUSTRAW 
ON ORDRAW.CUSTOMER_ID = CUSTRAW.CUSTOMER_ID